name: "matrix configuration"

on:
  workflow_dispatch:
  # push:

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: windows-latest
            images: alpine
        include:
          - os: ubuntu-latest
            images: amd64/alpine
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info
      - name: Run image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
