name: "matrix configuration"

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-20.04]
        images: [hello-world, alpine]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Echo Docker Details
          run: docker info
        - name: Run image on ${{ matrix.os }}
          run: docker run ${{ matrix.images }}
